version: '3'
services:
  web:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - '80:80'
      # - '443:443'
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf.template:ro
      - ./log/nginx:/var/log/nginx
      - ./www/html:/usr/share/www/html:ro
    environment:
      TZ: Asia/Tokyo
      NGINX_HOST: localhost
      PHP_PASS: 'php:9000'
    networks: 
      - front
    command: >
      /bin/sh -c
      "envsubst '$$NGINX_HOST$$PHP_PASS'
      < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
  
  php:
    image: php:7.3-fpm-alpine
    restart: always
    ports:
      - '9000:9000'
    networks: 
      - front
      - back

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: example
    networks:
      - back

networks:
  front:
  back: